-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.1
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity op_mem_read is
port (
    m_axi_din_gmem_V_AWVALID : OUT STD_LOGIC;
    m_axi_din_gmem_V_AWREADY : IN STD_LOGIC;
    m_axi_din_gmem_V_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_din_gmem_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_din_gmem_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_din_gmem_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_din_gmem_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_din_gmem_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_din_gmem_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_din_gmem_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_din_gmem_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_din_gmem_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_din_gmem_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_din_gmem_V_WVALID : OUT STD_LOGIC;
    m_axi_din_gmem_V_WREADY : IN STD_LOGIC;
    m_axi_din_gmem_V_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_din_gmem_V_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_din_gmem_V_WLAST : OUT STD_LOGIC;
    m_axi_din_gmem_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_din_gmem_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_din_gmem_V_ARVALID : OUT STD_LOGIC;
    m_axi_din_gmem_V_ARREADY : IN STD_LOGIC;
    m_axi_din_gmem_V_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_din_gmem_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_din_gmem_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_din_gmem_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_din_gmem_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_din_gmem_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_din_gmem_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_din_gmem_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_din_gmem_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_din_gmem_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_din_gmem_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_din_gmem_V_RVALID : IN STD_LOGIC;
    m_axi_din_gmem_V_RREADY : OUT STD_LOGIC;
    m_axi_din_gmem_V_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_din_gmem_V_RLAST : IN STD_LOGIC;
    m_axi_din_gmem_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_din_gmem_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_din_gmem_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_din_gmem_V_BVALID : IN STD_LOGIC;
    m_axi_din_gmem_V_BREADY : OUT STD_LOGIC;
    m_axi_din_gmem_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_din_gmem_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_din_gmem_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    mem_in_V_offset_dout : IN STD_LOGIC_VECTOR (57 downto 0);
    mem_in_V_offset_empty_n : IN STD_LOGIC;
    mem_in_V_offset_read : OUT STD_LOGIC;
    axis_m_0_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    axis_m_0_TSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    axis_m_0_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    enable_0_V_loc_chann : IN STD_LOGIC_VECTOR (0 downto 0);
    read_mem_config_offs : IN STD_LOGIC_VECTOR (63 downto 0);
    read_mem_config_size : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    enable_0_V_loc_chann_ap_vld : IN STD_LOGIC;
    axis_m_0_TVALID : OUT STD_LOGIC;
    axis_m_0_TREADY : IN STD_LOGIC;
    read_mem_config_offs_ap_vld : IN STD_LOGIC;
    read_mem_config_size_ap_vld : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of op_mem_read is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

    signal op_mem_read_Block_p_U0_ap_start : STD_LOGIC;
    signal op_mem_read_Block_p_U0_ap_done : STD_LOGIC;
    signal op_mem_read_Block_p_U0_ap_continue : STD_LOGIC;
    signal op_mem_read_Block_p_U0_ap_idle : STD_LOGIC;
    signal op_mem_read_Block_p_U0_ap_ready : STD_LOGIC;
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_AWVALID : STD_LOGIC;
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_WVALID : STD_LOGIC;
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_WDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_WSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_WLAST : STD_LOGIC;
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_ARVALID : STD_LOGIC;
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_RREADY : STD_LOGIC;
    signal op_mem_read_Block_p_U0_m_axi_mem_in_V_BREADY : STD_LOGIC;
    signal op_mem_read_Block_p_U0_mem_in_V_offset_read : STD_LOGIC;
    signal op_mem_read_Block_p_U0_axis_m_0_TDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal op_mem_read_Block_p_U0_axis_m_0_TVALID : STD_LOGIC;
    signal op_mem_read_Block_p_U0_axis_m_0_TSTRB : STD_LOGIC_VECTOR (7 downto 0);
    signal op_mem_read_Block_p_U0_axis_m_0_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sync_continue : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal op_mem_read_Block_p_U0_start_full_n : STD_LOGIC;
    signal op_mem_read_Block_p_U0_start_write : STD_LOGIC;

    component op_mem_read_Block_p IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        enable_0_V_loc_chann : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_AWVALID : OUT STD_LOGIC;
        m_axi_mem_in_V_AWREADY : IN STD_LOGIC;
        m_axi_mem_in_V_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_mem_in_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_mem_in_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_mem_in_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mem_in_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mem_in_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mem_in_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_mem_in_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mem_in_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mem_in_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_WVALID : OUT STD_LOGIC;
        m_axi_mem_in_V_WREADY : IN STD_LOGIC;
        m_axi_mem_in_V_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        m_axi_mem_in_V_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_mem_in_V_WLAST : OUT STD_LOGIC;
        m_axi_mem_in_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_ARVALID : OUT STD_LOGIC;
        m_axi_mem_in_V_ARREADY : IN STD_LOGIC;
        m_axi_mem_in_V_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_mem_in_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_mem_in_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_mem_in_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mem_in_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mem_in_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mem_in_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_mem_in_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mem_in_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mem_in_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_RVALID : IN STD_LOGIC;
        m_axi_mem_in_V_RREADY : OUT STD_LOGIC;
        m_axi_mem_in_V_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        m_axi_mem_in_V_RLAST : IN STD_LOGIC;
        m_axi_mem_in_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mem_in_V_BVALID : IN STD_LOGIC;
        m_axi_mem_in_V_BREADY : OUT STD_LOGIC;
        m_axi_mem_in_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mem_in_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        mem_in_V_offset_dout : IN STD_LOGIC_VECTOR (57 downto 0);
        mem_in_V_offset_empty_n : IN STD_LOGIC;
        mem_in_V_offset_read : OUT STD_LOGIC;
        axis_m_0_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        axis_m_0_TVALID : OUT STD_LOGIC;
        axis_m_0_TREADY : IN STD_LOGIC;
        axis_m_0_TSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
        axis_m_0_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        read_mem_config_offs : IN STD_LOGIC_VECTOR (63 downto 0);
        read_mem_config_size : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    op_mem_read_Block_p_U0 : component op_mem_read_Block_p
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => op_mem_read_Block_p_U0_ap_start,
        ap_done => op_mem_read_Block_p_U0_ap_done,
        ap_continue => op_mem_read_Block_p_U0_ap_continue,
        ap_idle => op_mem_read_Block_p_U0_ap_idle,
        ap_ready => op_mem_read_Block_p_U0_ap_ready,
        enable_0_V_loc_chann => enable_0_V_loc_chann,
        m_axi_mem_in_V_AWVALID => op_mem_read_Block_p_U0_m_axi_mem_in_V_AWVALID,
        m_axi_mem_in_V_AWREADY => ap_const_logic_0,
        m_axi_mem_in_V_AWADDR => op_mem_read_Block_p_U0_m_axi_mem_in_V_AWADDR,
        m_axi_mem_in_V_AWID => op_mem_read_Block_p_U0_m_axi_mem_in_V_AWID,
        m_axi_mem_in_V_AWLEN => op_mem_read_Block_p_U0_m_axi_mem_in_V_AWLEN,
        m_axi_mem_in_V_AWSIZE => op_mem_read_Block_p_U0_m_axi_mem_in_V_AWSIZE,
        m_axi_mem_in_V_AWBURST => op_mem_read_Block_p_U0_m_axi_mem_in_V_AWBURST,
        m_axi_mem_in_V_AWLOCK => op_mem_read_Block_p_U0_m_axi_mem_in_V_AWLOCK,
        m_axi_mem_in_V_AWCACHE => op_mem_read_Block_p_U0_m_axi_mem_in_V_AWCACHE,
        m_axi_mem_in_V_AWPROT => op_mem_read_Block_p_U0_m_axi_mem_in_V_AWPROT,
        m_axi_mem_in_V_AWQOS => op_mem_read_Block_p_U0_m_axi_mem_in_V_AWQOS,
        m_axi_mem_in_V_AWREGION => op_mem_read_Block_p_U0_m_axi_mem_in_V_AWREGION,
        m_axi_mem_in_V_AWUSER => op_mem_read_Block_p_U0_m_axi_mem_in_V_AWUSER,
        m_axi_mem_in_V_WVALID => op_mem_read_Block_p_U0_m_axi_mem_in_V_WVALID,
        m_axi_mem_in_V_WREADY => ap_const_logic_0,
        m_axi_mem_in_V_WDATA => op_mem_read_Block_p_U0_m_axi_mem_in_V_WDATA,
        m_axi_mem_in_V_WSTRB => op_mem_read_Block_p_U0_m_axi_mem_in_V_WSTRB,
        m_axi_mem_in_V_WLAST => op_mem_read_Block_p_U0_m_axi_mem_in_V_WLAST,
        m_axi_mem_in_V_WID => op_mem_read_Block_p_U0_m_axi_mem_in_V_WID,
        m_axi_mem_in_V_WUSER => op_mem_read_Block_p_U0_m_axi_mem_in_V_WUSER,
        m_axi_mem_in_V_ARVALID => op_mem_read_Block_p_U0_m_axi_mem_in_V_ARVALID,
        m_axi_mem_in_V_ARREADY => m_axi_din_gmem_V_ARREADY,
        m_axi_mem_in_V_ARADDR => op_mem_read_Block_p_U0_m_axi_mem_in_V_ARADDR,
        m_axi_mem_in_V_ARID => op_mem_read_Block_p_U0_m_axi_mem_in_V_ARID,
        m_axi_mem_in_V_ARLEN => op_mem_read_Block_p_U0_m_axi_mem_in_V_ARLEN,
        m_axi_mem_in_V_ARSIZE => op_mem_read_Block_p_U0_m_axi_mem_in_V_ARSIZE,
        m_axi_mem_in_V_ARBURST => op_mem_read_Block_p_U0_m_axi_mem_in_V_ARBURST,
        m_axi_mem_in_V_ARLOCK => op_mem_read_Block_p_U0_m_axi_mem_in_V_ARLOCK,
        m_axi_mem_in_V_ARCACHE => op_mem_read_Block_p_U0_m_axi_mem_in_V_ARCACHE,
        m_axi_mem_in_V_ARPROT => op_mem_read_Block_p_U0_m_axi_mem_in_V_ARPROT,
        m_axi_mem_in_V_ARQOS => op_mem_read_Block_p_U0_m_axi_mem_in_V_ARQOS,
        m_axi_mem_in_V_ARREGION => op_mem_read_Block_p_U0_m_axi_mem_in_V_ARREGION,
        m_axi_mem_in_V_ARUSER => op_mem_read_Block_p_U0_m_axi_mem_in_V_ARUSER,
        m_axi_mem_in_V_RVALID => m_axi_din_gmem_V_RVALID,
        m_axi_mem_in_V_RREADY => op_mem_read_Block_p_U0_m_axi_mem_in_V_RREADY,
        m_axi_mem_in_V_RDATA => m_axi_din_gmem_V_RDATA,
        m_axi_mem_in_V_RLAST => m_axi_din_gmem_V_RLAST,
        m_axi_mem_in_V_RID => m_axi_din_gmem_V_RID,
        m_axi_mem_in_V_RUSER => m_axi_din_gmem_V_RUSER,
        m_axi_mem_in_V_RRESP => m_axi_din_gmem_V_RRESP,
        m_axi_mem_in_V_BVALID => ap_const_logic_0,
        m_axi_mem_in_V_BREADY => op_mem_read_Block_p_U0_m_axi_mem_in_V_BREADY,
        m_axi_mem_in_V_BRESP => ap_const_lv2_0,
        m_axi_mem_in_V_BID => ap_const_lv1_0,
        m_axi_mem_in_V_BUSER => ap_const_lv1_0,
        mem_in_V_offset_dout => mem_in_V_offset_dout,
        mem_in_V_offset_empty_n => mem_in_V_offset_empty_n,
        mem_in_V_offset_read => op_mem_read_Block_p_U0_mem_in_V_offset_read,
        axis_m_0_TDATA => op_mem_read_Block_p_U0_axis_m_0_TDATA,
        axis_m_0_TVALID => op_mem_read_Block_p_U0_axis_m_0_TVALID,
        axis_m_0_TREADY => axis_m_0_TREADY,
        axis_m_0_TSTRB => op_mem_read_Block_p_U0_axis_m_0_TSTRB,
        axis_m_0_TLAST => op_mem_read_Block_p_U0_axis_m_0_TLAST,
        read_mem_config_offs => read_mem_config_offs,
        read_mem_config_size => read_mem_config_size);




    ap_done <= op_mem_read_Block_p_U0_ap_done;
    ap_idle <= op_mem_read_Block_p_U0_ap_idle;
    ap_ready <= op_mem_read_Block_p_U0_ap_ready;
    ap_sync_continue <= ap_continue;
    ap_sync_done <= op_mem_read_Block_p_U0_ap_done;
    ap_sync_ready <= op_mem_read_Block_p_U0_ap_ready;
    axis_m_0_TDATA <= op_mem_read_Block_p_U0_axis_m_0_TDATA;
    axis_m_0_TLAST <= op_mem_read_Block_p_U0_axis_m_0_TLAST;
    axis_m_0_TSTRB <= op_mem_read_Block_p_U0_axis_m_0_TSTRB;
    axis_m_0_TVALID <= op_mem_read_Block_p_U0_axis_m_0_TVALID;
    m_axi_din_gmem_V_ARADDR <= op_mem_read_Block_p_U0_m_axi_mem_in_V_ARADDR;
    m_axi_din_gmem_V_ARBURST <= op_mem_read_Block_p_U0_m_axi_mem_in_V_ARBURST;
    m_axi_din_gmem_V_ARCACHE <= op_mem_read_Block_p_U0_m_axi_mem_in_V_ARCACHE;
    m_axi_din_gmem_V_ARID <= op_mem_read_Block_p_U0_m_axi_mem_in_V_ARID;
    m_axi_din_gmem_V_ARLEN <= op_mem_read_Block_p_U0_m_axi_mem_in_V_ARLEN;
    m_axi_din_gmem_V_ARLOCK <= op_mem_read_Block_p_U0_m_axi_mem_in_V_ARLOCK;
    m_axi_din_gmem_V_ARPROT <= op_mem_read_Block_p_U0_m_axi_mem_in_V_ARPROT;
    m_axi_din_gmem_V_ARQOS <= op_mem_read_Block_p_U0_m_axi_mem_in_V_ARQOS;
    m_axi_din_gmem_V_ARREGION <= op_mem_read_Block_p_U0_m_axi_mem_in_V_ARREGION;
    m_axi_din_gmem_V_ARSIZE <= op_mem_read_Block_p_U0_m_axi_mem_in_V_ARSIZE;
    m_axi_din_gmem_V_ARUSER <= op_mem_read_Block_p_U0_m_axi_mem_in_V_ARUSER;
    m_axi_din_gmem_V_ARVALID <= op_mem_read_Block_p_U0_m_axi_mem_in_V_ARVALID;
    m_axi_din_gmem_V_AWADDR <= ap_const_lv64_0;
    m_axi_din_gmem_V_AWBURST <= ap_const_lv2_0;
    m_axi_din_gmem_V_AWCACHE <= ap_const_lv4_0;
    m_axi_din_gmem_V_AWID <= ap_const_lv1_0;
    m_axi_din_gmem_V_AWLEN <= ap_const_lv32_0;
    m_axi_din_gmem_V_AWLOCK <= ap_const_lv2_0;
    m_axi_din_gmem_V_AWPROT <= ap_const_lv3_0;
    m_axi_din_gmem_V_AWQOS <= ap_const_lv4_0;
    m_axi_din_gmem_V_AWREGION <= ap_const_lv4_0;
    m_axi_din_gmem_V_AWSIZE <= ap_const_lv3_0;
    m_axi_din_gmem_V_AWUSER <= ap_const_lv1_0;
    m_axi_din_gmem_V_AWVALID <= ap_const_logic_0;
    m_axi_din_gmem_V_BREADY <= ap_const_logic_0;
    m_axi_din_gmem_V_RREADY <= op_mem_read_Block_p_U0_m_axi_mem_in_V_RREADY;
    m_axi_din_gmem_V_WDATA <= ap_const_lv512_lc_1;
    m_axi_din_gmem_V_WID <= ap_const_lv1_0;
    m_axi_din_gmem_V_WLAST <= ap_const_logic_0;
    m_axi_din_gmem_V_WSTRB <= ap_const_lv64_0;
    m_axi_din_gmem_V_WUSER <= ap_const_lv1_0;
    m_axi_din_gmem_V_WVALID <= ap_const_logic_0;
    mem_in_V_offset_read <= op_mem_read_Block_p_U0_mem_in_V_offset_read;
    op_mem_read_Block_p_U0_ap_continue <= ap_continue;
    op_mem_read_Block_p_U0_ap_start <= ap_start;
    op_mem_read_Block_p_U0_start_full_n <= ap_const_logic_1;
    op_mem_read_Block_p_U0_start_write <= ap_const_logic_0;
end behav;
