-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.1
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity op_mem_write is
port (
    axis_s_0_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    axis_s_0_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    axis_s_0_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dout_gmem_V_AWVALID : OUT STD_LOGIC;
    m_axi_dout_gmem_V_AWREADY : IN STD_LOGIC;
    m_axi_dout_gmem_V_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_dout_gmem_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dout_gmem_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_dout_gmem_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_dout_gmem_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dout_gmem_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dout_gmem_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dout_gmem_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_dout_gmem_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dout_gmem_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dout_gmem_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dout_gmem_V_WVALID : OUT STD_LOGIC;
    m_axi_dout_gmem_V_WREADY : IN STD_LOGIC;
    m_axi_dout_gmem_V_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_dout_gmem_V_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_dout_gmem_V_WLAST : OUT STD_LOGIC;
    m_axi_dout_gmem_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dout_gmem_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dout_gmem_V_ARVALID : OUT STD_LOGIC;
    m_axi_dout_gmem_V_ARREADY : IN STD_LOGIC;
    m_axi_dout_gmem_V_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_dout_gmem_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dout_gmem_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_dout_gmem_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_dout_gmem_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dout_gmem_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dout_gmem_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dout_gmem_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_dout_gmem_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dout_gmem_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dout_gmem_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dout_gmem_V_RVALID : IN STD_LOGIC;
    m_axi_dout_gmem_V_RREADY : OUT STD_LOGIC;
    m_axi_dout_gmem_V_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_dout_gmem_V_RLAST : IN STD_LOGIC;
    m_axi_dout_gmem_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dout_gmem_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dout_gmem_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dout_gmem_V_BVALID : IN STD_LOGIC;
    m_axi_dout_gmem_V_BREADY : OUT STD_LOGIC;
    m_axi_dout_gmem_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dout_gmem_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dout_gmem_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    mem_out_V_offset_dout : IN STD_LOGIC_VECTOR (57 downto 0);
    mem_out_V_offset_empty_n : IN STD_LOGIC;
    mem_out_V_offset_read : OUT STD_LOGIC;
    enable_1_V_loc_chann : IN STD_LOGIC_VECTOR (0 downto 0);
    write_mem_config_off : IN STD_LOGIC_VECTOR (63 downto 0);
    write_mem_config_siz : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    enable_1_V_loc_chann_ap_vld : IN STD_LOGIC;
    axis_s_0_TVALID : IN STD_LOGIC;
    axis_s_0_TREADY : OUT STD_LOGIC;
    write_mem_config_off_ap_vld : IN STD_LOGIC;
    write_mem_config_siz_ap_vld : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of op_mem_write is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv512_lc_2 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

    signal op_mem_write_Block_U0_ap_start : STD_LOGIC;
    signal op_mem_write_Block_U0_ap_done : STD_LOGIC;
    signal op_mem_write_Block_U0_ap_continue : STD_LOGIC;
    signal op_mem_write_Block_U0_ap_idle : STD_LOGIC;
    signal op_mem_write_Block_U0_ap_ready : STD_LOGIC;
    signal op_mem_write_Block_U0_axis_s_0_TREADY : STD_LOGIC;
    signal op_mem_write_Block_U0_m_axi_mem_in_V_AWVALID : STD_LOGIC;
    signal op_mem_write_Block_U0_m_axi_mem_in_V_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_WVALID : STD_LOGIC;
    signal op_mem_write_Block_U0_m_axi_mem_in_V_WDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_WSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_WLAST : STD_LOGIC;
    signal op_mem_write_Block_U0_m_axi_mem_in_V_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_ARVALID : STD_LOGIC;
    signal op_mem_write_Block_U0_m_axi_mem_in_V_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal op_mem_write_Block_U0_m_axi_mem_in_V_RREADY : STD_LOGIC;
    signal op_mem_write_Block_U0_m_axi_mem_in_V_BREADY : STD_LOGIC;
    signal op_mem_write_Block_U0_mem_out_V_offset_read : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal op_mem_write_Block_U0_start_full_n : STD_LOGIC;
    signal op_mem_write_Block_U0_start_write : STD_LOGIC;

    component op_mem_write_Block_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        enable_1_V_loc_chann : IN STD_LOGIC_VECTOR (0 downto 0);
        axis_s_0_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        axis_s_0_TVALID : IN STD_LOGIC;
        axis_s_0_TREADY : OUT STD_LOGIC;
        axis_s_0_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        axis_s_0_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_AWVALID : OUT STD_LOGIC;
        m_axi_mem_in_V_AWREADY : IN STD_LOGIC;
        m_axi_mem_in_V_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_mem_in_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_mem_in_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_mem_in_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mem_in_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mem_in_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mem_in_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_mem_in_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mem_in_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mem_in_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_WVALID : OUT STD_LOGIC;
        m_axi_mem_in_V_WREADY : IN STD_LOGIC;
        m_axi_mem_in_V_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        m_axi_mem_in_V_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_mem_in_V_WLAST : OUT STD_LOGIC;
        m_axi_mem_in_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_ARVALID : OUT STD_LOGIC;
        m_axi_mem_in_V_ARREADY : IN STD_LOGIC;
        m_axi_mem_in_V_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_mem_in_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_mem_in_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_mem_in_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mem_in_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mem_in_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mem_in_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_mem_in_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mem_in_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_mem_in_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_RVALID : IN STD_LOGIC;
        m_axi_mem_in_V_RREADY : OUT STD_LOGIC;
        m_axi_mem_in_V_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        m_axi_mem_in_V_RLAST : IN STD_LOGIC;
        m_axi_mem_in_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mem_in_V_BVALID : IN STD_LOGIC;
        m_axi_mem_in_V_BREADY : OUT STD_LOGIC;
        m_axi_mem_in_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_mem_in_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_mem_in_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        mem_out_V_offset_dout : IN STD_LOGIC_VECTOR (57 downto 0);
        mem_out_V_offset_empty_n : IN STD_LOGIC;
        mem_out_V_offset_read : OUT STD_LOGIC;
        write_mem_config_off : IN STD_LOGIC_VECTOR (63 downto 0);
        write_mem_config_siz : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    op_mem_write_Block_U0 : component op_mem_write_Block_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => op_mem_write_Block_U0_ap_start,
        ap_done => op_mem_write_Block_U0_ap_done,
        ap_continue => op_mem_write_Block_U0_ap_continue,
        ap_idle => op_mem_write_Block_U0_ap_idle,
        ap_ready => op_mem_write_Block_U0_ap_ready,
        enable_1_V_loc_chann => enable_1_V_loc_chann,
        axis_s_0_TDATA => axis_s_0_TDATA,
        axis_s_0_TVALID => axis_s_0_TVALID,
        axis_s_0_TREADY => op_mem_write_Block_U0_axis_s_0_TREADY,
        axis_s_0_TSTRB => axis_s_0_TSTRB,
        axis_s_0_TLAST => axis_s_0_TLAST,
        m_axi_mem_in_V_AWVALID => op_mem_write_Block_U0_m_axi_mem_in_V_AWVALID,
        m_axi_mem_in_V_AWREADY => m_axi_dout_gmem_V_AWREADY,
        m_axi_mem_in_V_AWADDR => op_mem_write_Block_U0_m_axi_mem_in_V_AWADDR,
        m_axi_mem_in_V_AWID => op_mem_write_Block_U0_m_axi_mem_in_V_AWID,
        m_axi_mem_in_V_AWLEN => op_mem_write_Block_U0_m_axi_mem_in_V_AWLEN,
        m_axi_mem_in_V_AWSIZE => op_mem_write_Block_U0_m_axi_mem_in_V_AWSIZE,
        m_axi_mem_in_V_AWBURST => op_mem_write_Block_U0_m_axi_mem_in_V_AWBURST,
        m_axi_mem_in_V_AWLOCK => op_mem_write_Block_U0_m_axi_mem_in_V_AWLOCK,
        m_axi_mem_in_V_AWCACHE => op_mem_write_Block_U0_m_axi_mem_in_V_AWCACHE,
        m_axi_mem_in_V_AWPROT => op_mem_write_Block_U0_m_axi_mem_in_V_AWPROT,
        m_axi_mem_in_V_AWQOS => op_mem_write_Block_U0_m_axi_mem_in_V_AWQOS,
        m_axi_mem_in_V_AWREGION => op_mem_write_Block_U0_m_axi_mem_in_V_AWREGION,
        m_axi_mem_in_V_AWUSER => op_mem_write_Block_U0_m_axi_mem_in_V_AWUSER,
        m_axi_mem_in_V_WVALID => op_mem_write_Block_U0_m_axi_mem_in_V_WVALID,
        m_axi_mem_in_V_WREADY => m_axi_dout_gmem_V_WREADY,
        m_axi_mem_in_V_WDATA => op_mem_write_Block_U0_m_axi_mem_in_V_WDATA,
        m_axi_mem_in_V_WSTRB => op_mem_write_Block_U0_m_axi_mem_in_V_WSTRB,
        m_axi_mem_in_V_WLAST => op_mem_write_Block_U0_m_axi_mem_in_V_WLAST,
        m_axi_mem_in_V_WID => op_mem_write_Block_U0_m_axi_mem_in_V_WID,
        m_axi_mem_in_V_WUSER => op_mem_write_Block_U0_m_axi_mem_in_V_WUSER,
        m_axi_mem_in_V_ARVALID => op_mem_write_Block_U0_m_axi_mem_in_V_ARVALID,
        m_axi_mem_in_V_ARREADY => ap_const_logic_0,
        m_axi_mem_in_V_ARADDR => op_mem_write_Block_U0_m_axi_mem_in_V_ARADDR,
        m_axi_mem_in_V_ARID => op_mem_write_Block_U0_m_axi_mem_in_V_ARID,
        m_axi_mem_in_V_ARLEN => op_mem_write_Block_U0_m_axi_mem_in_V_ARLEN,
        m_axi_mem_in_V_ARSIZE => op_mem_write_Block_U0_m_axi_mem_in_V_ARSIZE,
        m_axi_mem_in_V_ARBURST => op_mem_write_Block_U0_m_axi_mem_in_V_ARBURST,
        m_axi_mem_in_V_ARLOCK => op_mem_write_Block_U0_m_axi_mem_in_V_ARLOCK,
        m_axi_mem_in_V_ARCACHE => op_mem_write_Block_U0_m_axi_mem_in_V_ARCACHE,
        m_axi_mem_in_V_ARPROT => op_mem_write_Block_U0_m_axi_mem_in_V_ARPROT,
        m_axi_mem_in_V_ARQOS => op_mem_write_Block_U0_m_axi_mem_in_V_ARQOS,
        m_axi_mem_in_V_ARREGION => op_mem_write_Block_U0_m_axi_mem_in_V_ARREGION,
        m_axi_mem_in_V_ARUSER => op_mem_write_Block_U0_m_axi_mem_in_V_ARUSER,
        m_axi_mem_in_V_RVALID => ap_const_logic_0,
        m_axi_mem_in_V_RREADY => op_mem_write_Block_U0_m_axi_mem_in_V_RREADY,
        m_axi_mem_in_V_RDATA => ap_const_lv512_lc_1,
        m_axi_mem_in_V_RLAST => ap_const_logic_0,
        m_axi_mem_in_V_RID => ap_const_lv1_0,
        m_axi_mem_in_V_RUSER => ap_const_lv1_0,
        m_axi_mem_in_V_RRESP => ap_const_lv2_0,
        m_axi_mem_in_V_BVALID => m_axi_dout_gmem_V_BVALID,
        m_axi_mem_in_V_BREADY => op_mem_write_Block_U0_m_axi_mem_in_V_BREADY,
        m_axi_mem_in_V_BRESP => m_axi_dout_gmem_V_BRESP,
        m_axi_mem_in_V_BID => m_axi_dout_gmem_V_BID,
        m_axi_mem_in_V_BUSER => m_axi_dout_gmem_V_BUSER,
        mem_out_V_offset_dout => mem_out_V_offset_dout,
        mem_out_V_offset_empty_n => mem_out_V_offset_empty_n,
        mem_out_V_offset_read => op_mem_write_Block_U0_mem_out_V_offset_read,
        write_mem_config_off => write_mem_config_off,
        write_mem_config_siz => write_mem_config_siz);




    ap_done <= op_mem_write_Block_U0_ap_done;
    ap_idle <= op_mem_write_Block_U0_ap_idle;
    ap_ready <= op_mem_write_Block_U0_ap_ready;
    ap_sync_continue <= ap_continue;
    ap_sync_done <= op_mem_write_Block_U0_ap_done;
    ap_sync_ready <= op_mem_write_Block_U0_ap_ready;
    axis_s_0_TREADY <= op_mem_write_Block_U0_axis_s_0_TREADY;
    m_axi_dout_gmem_V_ARADDR <= ap_const_lv64_0;
    m_axi_dout_gmem_V_ARBURST <= ap_const_lv2_0;
    m_axi_dout_gmem_V_ARCACHE <= ap_const_lv4_0;
    m_axi_dout_gmem_V_ARID <= ap_const_lv1_0;
    m_axi_dout_gmem_V_ARLEN <= ap_const_lv32_0;
    m_axi_dout_gmem_V_ARLOCK <= ap_const_lv2_0;
    m_axi_dout_gmem_V_ARPROT <= ap_const_lv3_0;
    m_axi_dout_gmem_V_ARQOS <= ap_const_lv4_0;
    m_axi_dout_gmem_V_ARREGION <= ap_const_lv4_0;
    m_axi_dout_gmem_V_ARSIZE <= ap_const_lv3_0;
    m_axi_dout_gmem_V_ARUSER <= ap_const_lv1_0;
    m_axi_dout_gmem_V_ARVALID <= ap_const_logic_0;
    m_axi_dout_gmem_V_AWADDR <= op_mem_write_Block_U0_m_axi_mem_in_V_AWADDR;
    m_axi_dout_gmem_V_AWBURST <= op_mem_write_Block_U0_m_axi_mem_in_V_AWBURST;
    m_axi_dout_gmem_V_AWCACHE <= op_mem_write_Block_U0_m_axi_mem_in_V_AWCACHE;
    m_axi_dout_gmem_V_AWID <= op_mem_write_Block_U0_m_axi_mem_in_V_AWID;
    m_axi_dout_gmem_V_AWLEN <= op_mem_write_Block_U0_m_axi_mem_in_V_AWLEN;
    m_axi_dout_gmem_V_AWLOCK <= op_mem_write_Block_U0_m_axi_mem_in_V_AWLOCK;
    m_axi_dout_gmem_V_AWPROT <= op_mem_write_Block_U0_m_axi_mem_in_V_AWPROT;
    m_axi_dout_gmem_V_AWQOS <= op_mem_write_Block_U0_m_axi_mem_in_V_AWQOS;
    m_axi_dout_gmem_V_AWREGION <= op_mem_write_Block_U0_m_axi_mem_in_V_AWREGION;
    m_axi_dout_gmem_V_AWSIZE <= op_mem_write_Block_U0_m_axi_mem_in_V_AWSIZE;
    m_axi_dout_gmem_V_AWUSER <= op_mem_write_Block_U0_m_axi_mem_in_V_AWUSER;
    m_axi_dout_gmem_V_AWVALID <= op_mem_write_Block_U0_m_axi_mem_in_V_AWVALID;
    m_axi_dout_gmem_V_BREADY <= op_mem_write_Block_U0_m_axi_mem_in_V_BREADY;
    m_axi_dout_gmem_V_RREADY <= ap_const_logic_0;
    m_axi_dout_gmem_V_WDATA <= op_mem_write_Block_U0_m_axi_mem_in_V_WDATA;
    m_axi_dout_gmem_V_WID <= op_mem_write_Block_U0_m_axi_mem_in_V_WID;
    m_axi_dout_gmem_V_WLAST <= op_mem_write_Block_U0_m_axi_mem_in_V_WLAST;
    m_axi_dout_gmem_V_WSTRB <= op_mem_write_Block_U0_m_axi_mem_in_V_WSTRB;
    m_axi_dout_gmem_V_WUSER <= op_mem_write_Block_U0_m_axi_mem_in_V_WUSER;
    m_axi_dout_gmem_V_WVALID <= op_mem_write_Block_U0_m_axi_mem_in_V_WVALID;
    mem_out_V_offset_read <= op_mem_write_Block_U0_mem_out_V_offset_read;
    op_mem_write_Block_U0_ap_continue <= ap_continue;
    op_mem_write_Block_U0_ap_start <= ap_start;
    op_mem_write_Block_U0_start_full_n <= ap_const_logic_1;
    op_mem_write_Block_U0_start_write <= ap_const_logic_0;
end behav;
